In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/preprocessed_data.csv")

df.head()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount,Year,Month,Day,Week,Quarter,DayOfWeek,Weekend,Season
0,109318,C,7,80.079844,2023-12-26 12:32:00,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764,2023,12,26,52,4,Tuesday,False,Winter
1,993229,C,4,75.195229,2023-08-05 00:00:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546,2023,8,5,31,3,Saturday,True,Monsoon
2,579675,A,8,31.528816,2024-03-11 18:51:00,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651,2024,3,11,11,1,Monday,False,Summer
3,799826,D,5,98.880218,2023-10-27 22:00:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769,2023,10,27,43,4,Friday,False,Autumn
4,121413,A,7,93.188512,2023-12-22 11:38:00,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484,2023,12,22,51,4,Friday,False,Winter

In [3]:
df["ProductID"].value_counts()

ProductID
C    25209
D    25042
B    24997
A    24752
Name: count, dtype: int64

In [4]:
product_counts = (
    df["ProductID"]
    .value_counts()
    .reset_index()
)

product_counts.columns = [
    "ProductID",
    "PurchaseCount"
]

product_counts

  ProductID  PurchaseCount
0         C          25209
1         D          25042
2         B          24997
3         A          24752

In [5]:
def recommend_products(product_id, top_n=3):

    recommendations = product_counts[
        product_counts["ProductID"] != product_id
    ].head(top_n)

    return recommendations

In [7]:
product_counts.to_csv(
    "../data/product_recommendations.csv",
    index=False
)

print("Recommendation data saved successfully!")

Recommendation data saved successfully!